version: '3.7'
services:
  node1:
    build: .
    command: python -u script.py "mongo-db" "1"
    ports:
      - 5000:5000
    volumes:
      - .:/todo 
    links:
      - db

  db:
    image: mongo:latest
    hostname: mongo-db
    ports:
      - 27017:27017
